#- name: Add APT key
#  apt_key:
#    id: "EA312927"
#    keyserver: keyserver.ubuntu.com
#  tags: install
#
#- name: Add APT repository
#  apt_repository:
#    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
#    state: present
#  tags: install
#
#- name: Install mongodb package
#  apt:
#    name: mongodb-org
#    state: present
#  tags: install
#
#- name: Configure service supervisor
#  systemd:
#    name: mongod
#    enabled: yes
#    state: started
#  tags: install



---
#- name: Install MongoDB 3.2
##  hosts: all
#  hosts: {{ hostname }}
#  become: true
#  tasks:
  # Добавим ключ репозитория для последующей работы с ним
  - name: Add APT key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com
    tags: install

  # Подключаем репозиторий с пакетами mongodb
  - name: Add APT repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
    tags: install

  # Выполним установку пакета
  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present
      force: yes
    tags: install

  # Включаем сервис
  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes
      daemon_reload: true
      state: started
    tags: install
